# Generated by Django 2.0.7 on 2018-10-30 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gymnasium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Gymnasium name')),
                ('address', models.CharField(max_length=255, verbose_name='Gymnasium address')),
                ('city', models.CharField(max_length=255, verbose_name='Gymnasium city')),
                ('zip_code', models.IntegerField(verbose_name='Gymnasium zip code')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='This is not a correct phone number', regex='^(?:(?:\\+|00)33|0)\\s*[1-7,9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='phone number')),
                ('surface', models.SmallIntegerField(blank=True, null=True, verbose_name='gymnasium surface')),
                ('capacity', models.SmallIntegerField(blank=True, null=True, verbose_name='gymnasium capacity')),
            ],
            options={
                'verbose_name': 'gymnasium',
                'verbose_name_plural': 'gymnasiums',
                'ordering': ('name', 'city'),
            },
        ),
    ]
